# Generated by Django 3.0.8 on 2020-07-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_music_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='cat',
            new_name='category',
        ),
    ]
