# Generated by Django 3.0.8 on 2020-07-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('audio', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
