# Generated by Django 3.0.8 on 2020-07-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='image',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
