# Generated by Django 3.0.8 on 2020-07-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='desc',
            field=models.CharField(default=0, max_length=999999),
            preserve_default=False,
        ),
    ]
