# Generated by Django 3.0.8 on 2020-07-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cat',
            field=models.CharField(default=0, max_length=1025),
            preserve_default=False,
        ),
    ]
